services:
  app:
    image: silentquest:dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/var/www
      - /var/www/vendor    # Prevents overwriting vendor directory
      - /var/www/node_modules  # Prevents overwriting node_modules

      - ./storage/app/public/:/ var/www/storage/app/public/

    ports:
      - "5173:5173"  # Vite (React frontend)
    env_file:
      - .env
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
    command: ["sh", "-c", "php artisan storage:link &&  php-fpm -F "]



  db:
    image: mysql:8.0  # Use official MySQL image
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "[Bananapeel16]"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/silentQuest.conf:/etc/nginx/conf.d/silentQuest.conf
      - ./public:/var/www/public
      - ./storage/app/public:/var/www/public/storage
      - ./storage:/var/www/storage
    ports:
      - "80:80"
    depends_on:
      - app
    command: [ "sh", "-c", "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" ]


volumes:
  mysql_data:

